pre_registration/Models/ViewModels/MyCuponsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pre_registration.Models.ViewModels
{
    public class MyCuponsViewModel
    {
        public int id { get; set; }
        public string orderDate { get; set; }
        public string cuponDate { get; set; }
        public string cuponTime { get; set; }

        public string Coment { get; set; }
        public string DeniedKey { get; set; }
    }
}

pre_registration/Models/ViewModels/SetCuponIntervalViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace pre_registration.Models.ViewModels
{
    public class SetCuponIntervalViewModel: RemoveCuponsModel
    {
        
        [Display(Name = "Часы")]
        public int beginTimeHours { get; set; }
        [Display(Name = "Мин.")]
        public int beginTimeMins { get; set; }
        [Display(Name = "Часы")]
        public int endTimeHours { get; set; }
        [Display(Name = "Мин.")]
        public int endTimeMins { get; set; }
        [Display(Name = "Интервал, мин.")]
        public int interval { get; set; }
       
    }
}

pre_registration/Controllers/CuponController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using pre_registration.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using pre_registration.Models.ViewModels;
using pre_registration.Models.DataBaseModel;
using System.Security.Claims;
using pre_registration.Services;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Authorization;

namespace pre_registration.Controllers
{
    public class CuponController : Controller
    {
        ApplicationContext db;
        private readonly IOptions<AppConfig> config;
        public IActionResult Index()
        {
            return View();
        }
        public  CuponController (ApplicationContext context, IOptions<AppConfig> config)
        {
            db = context;
            this.config = config;
        }
      
        public List<CuponDate> getFreeCupons(int areaId)
        {
            List<Order> orders = db.Orders.ToList();
            List<CuponDate> allCuponList = db.CuponDates.Where(x => x.Area.Id == areaId).ToList();
            List<CuponDate> busyCupons = new List<CuponDate>();


            foreach (var cupon in allCuponList)
            {
                foreach (var order in orders)
                {
                    if (cupon.id == order.CuponDateId)
                        busyCupons.Add(cupon);
                }
            }
            return allCuponList.Except(busyCupons).ToList();

        }
        public IActionResult viewCalendar(int areaId)
        { 
       
            //List<Order> orders = db.Orders.ToList();
            //List<CuponDate> allCuponList =  db.CuponDates.Where(x => x.Area.Id == areaId).ToList();
            //List<CuponDate> busyCupons = new List<CuponDate>();
            

            //    foreach (var cupon in allCuponList)
            //    {
            //        foreach (var order in orders)
            //        {
            //            if (cupon.id == order.CuponDateId)
            //                busyCupons.Add(cupon);
            //        }
            //    }
            List<CuponDate> model = getFreeCupons(areaId);//allCuponList.Except(busyCupons).ToList();
            if (areaId != 0)
                HttpContext.Session.SetInt32("Area", areaId);
            ViewBag.SelectedArea = areaId;
            return PartialView(model);
        }
        public IActionResult viewTimeWithOutRegistration()
        {
            int? areaId = HttpContext.Session.GetInt32("Area");
            DateTime selectedDate = new DateTime();
            DateTime.TryParse(HttpContext.Session.GetString("Date"), out selectedDate);
            List <CuponDate> model = db.CuponDates.Where(x => x.Area.Id == areaId && x.date.Date == selectedDate.Date).ToList();
            return PartialView("viewTime", model);
        }
        public IActionResult viewTime(DateTime selectedDay, int areaId)
        {
            System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("ru-RU");
            HttpContext.Session.SetString("Date", selectedDay.ToString("d"));
            var a = HttpContext.Session.GetString("continueWithOutRegistration");
            bool continueWithOutRegistration = false;
            continueWithOutRegistration = true; //bool.TryParse(HttpContext.Session.GetString("continueWithOutRegistration"), out continueWithOutRegistration);
            if (User.Identity.IsAuthenticated || continueWithOutRegistration)
            {                 
                DateTime d = selectedDay.Date;
                List<CuponDate> model = getFreeCupons(areaId).Where(x => x.date.Date == selectedDay.Date).ToList();//db.CuponDates.Where(x => x.Area.Id == areaId && x.date.Date == selectedDay.Date).ToList();
                model = model.OrderBy(x => x.date).ToList();
                return PartialView(model);
            }
            else
            {
                return RedirectToAction("LoginOrContinue", "Account");
            }
        }
        [Authorize(Roles = "admin, superuser")]
        public IActionResult viewRegisterCupons()
        {
            
            List<Order> orders;
            if (User.Identity.IsAuthenticated && User.IsInRole("superuser"))
            {
                var user = db.Users.FirstOrDefault(x => x.Login == User.Identity.Name);
                orders = db.Orders.Where(x => x.CuponDate.AreaId == user.AreaId.Value && x.CuponDate.date > DateTime.Now).ToList();
            }
            else
                orders = db.Orders.Where(x => x.CuponDate.date > DateTime.Now).ToList();

            foreach (var item in orders)
            {
                item.Client = db.Clients.First(x => x.id == item.ClientId);
                item.CuponDate = db.CuponDates.First(x => x.id == item.CuponDateId);
                item.Client.UserData = db.UsersData.First(x => x.id == item.Client.UserDataID);
                item.CuponDate.Area = db.Areas.FirstOrDefault(x => x.Id == item.CuponDate.AreaId);
            }
            orders = orders.OrderBy(x => x.CuponDate.date).ToList();
            return View(orders);
            
        }
        [Authorize(Roles = "admin, superuser")]
        public IActionResult setCuponInterval()
        {
            SetCuponIntervalViewModel model = new SetCuponIntervalViewModel();
            model.daysOfWeek = new bool[7];
            ViewBag.Hours = new List<int>();
            ViewBag.Mins = new List<int>();
            for (int i = 0; i < 24; i++)
                ViewBag.Hours.Add(i + 1);
            for (int i = 0; i < 60; i++)
                ViewBag.Mins.Add(i);
            ViewBag.Areas = db.Areas.ToList();
            return View();
        }
        [Authorize(Roles = "admin, superuser")]
        [HttpPost]
        public IActionResult setCuponInterval(SetCuponIntervalViewModel model)
        {
            if (model.beginDate > model.endDate)
            {

                ModelState.AddModelError("", "Ошибка! Дата начала периода не может быть позже даты окончания");
                ViewBag.Hours = new List<int>();
                ViewBag.Mins = new List<int>();
                for (int i = 0; i < 24; i++)
                    ViewBag.Hours.Add(i + 1);
                for (int i = 0; i < 60; i++)
                    ViewBag.Mins.Add(i);
                ViewBag.Areas = db.Areas.ToList();
                return View(model);               
            }
            if (User.Identity.IsAuthenticated && User.IsInRole("superuser"))
            {
                var user = db.Users.FirstOrDefault(x => x.Login == User.Identity.Name);
                model.AreaId = user.AreaId.Value;
            }
          //  int interval = 0;
            //bool isCorrectInterval = int.TryParse(model.interval, interval);
          //  if (model.interval)
            DateTime tempDate = model.beginDate;
            while (model.endDate >= tempDate)
            {
                DateTime tempBeginTime = new DateTime(tempDate.Year, tempDate.Month, tempDate.Day, model.beginTimeHours, model.beginTimeMins, 0);
                DateTime tempEndTime = new DateTime(tempDate.Year, tempDate.Month, tempDate.Day, model.endTimeHours, model.endTimeMins, 0);
                var a = (int)tempBeginTime.DayOfWeek;
                if (model.daysOfWeek[(int)tempBeginTime.DayOfWeek])
                    while (tempBeginTime <= tempEndTime)
                    {

                        db.CuponDates.Add(new CuponDate() { Area = db.Areas.First(x => x.Id == model.AreaId), date = tempBeginTime });

                        tempBeginTime= tempBeginTime.AddMinutes(model.interval);


                    }
                tempDate = tempDate.AddDays(1);
            }
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
        [HttpGet]
        [Authorize(Roles = "admin, superuser")]
        public ActionResult RemoveCupons()
        {
            RemoveCuponsModel model = new RemoveCuponsModel();
            model.daysOfWeek = new bool[7];
            ViewBag.Areas = db.Areas.ToList();
            return View(model);
        }
        [Authorize(Roles = "admin, superuser")]
        public ActionResult RemoveCupons(RemoveCuponsModel model)
        {
            if (User.Identity.IsAuthenticated && User.IsInRole("superuser"))
            {
                var user = db.Users.FirstOrDefault(x => x.Login == User.Identity.Name);
                model.AreaId = user.AreaId.Value;
            }
            RemoveCuponsMethod(model);
            return RedirectToAction("Index", "Home");
        }
        void RemoveCuponsMethod(RemoveCuponsModel model)
        {
           
            bool isNotSelectedDays = true;
            for (int i = 0; i < model.daysOfWeek.Count(); i++)
            {
                if (model.daysOfWeek[i] == true)
                {
                    isNotSelectedDays = true;
                    break;
                }
            }
            List<CuponDate> removeList = new List<CuponDate>();
            DateTime tempDate = model.beginDate;
            while (model.endDate >= tempDate)
            {
                DateTime tempBeginTime = new DateTime(tempDate.Year, tempDate.Month, tempDate.Day, 0, 0, 0);
                DateTime tempEndTime = new DateTime(tempDate.Year, tempDate.Month, tempDate.Day, 23, 59, 59);
                var a = (int)tempBeginTime.DayOfWeek;
                if (model.daysOfWeek[(int)tempBeginTime.DayOfWeek] || isNotSelectedDays)
                {
                    removeList.AddRange(db.CuponDates.Where(x => x.AreaId == model.AreaId && x.date > tempBeginTime && x.date < tempEndTime).ToList());

                }
                tempDate = tempDate.AddDays(1);
            }
            foreach (var item in removeList)
            {
                if (db.Orders.Where(x => x.CuponDateId == item.id).Count() > 0)

pre_registration/Views/Cupon/MyCupons.cshtml
@model List<pre_registration.Models.ViewModels.MyCuponsViewModel>
@{ 
    System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("ru-RU");
}
<h2 class="titleHeadRow">Мои талоны</h2>
<table class="table ">
    <tr>
        <th style="text-align:center">Дата записи</th>
        <th style="text-align:center">Дата талона</th>
        <th style="text-align:center">Время талона</th>
        <th style="text-align:center">Вопрос</th>
        <th style="text-align:center"></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>


            <td>@item.orderDate</td>
            <td>@item.cuponDate</td>
            <td>@item.cuponTime</td>
            <td>@item.Coment</td>
            <td>
                @if (DateTime.Parse(item.cuponDate) > DateTime.Now)
                {
                    <a class="cancelButton" asp-action="DeniedCupon" asp-controller="Cupon" asp-route-key="@item.DeniedKey">Отменить</a>

                }
            </td>
        </tr>
    }
</table>

pre_registration/Views/Cupon/RemoveCupons.cshtml
@model pre_registration.Models.ViewModels.RemoveCuponsModel
<h2 class="titleHeadRow">Удаление талонов для записи</h2>
<div>
    <div class="validation" asp-validation-summary="ModelOnly"></div>
    <form method="post" asp-controller="Cupon" asp-action="RemoveCupons" class="contentForm">

        @if (User.IsInRole("admin"))
        {
            <div class="contentDiv">
                <label asp-for="AreaId"></label><br />
                <select asp-for="AreaId" asp-items='new SelectList(ViewBag.Areas, "Id", "Name")' class="selectList"></select>
            </div>
        }
        <div>
            <label asp-for="beginDate"></label><br />
            <input type="date" asp-for="beginDate" value=""  />
        </div>
        <div>
            <label asp-for="endDate"></label><br />
            <input type="date" asp-for="endDate" value="" />
        </div>

        <div class="contentDiv">
            пн<input type="checkbox" asp-for="daysOfWeek[1]" />
            вт <input type="checkbox" asp-for="daysOfWeek[2]" />
            ср<input type="checkbox" asp-for="daysOfWeek[3]" />
            чт <input type="checkbox" asp-for="daysOfWeek[4]" />
            пт <input type="checkbox" asp-for="daysOfWeek[5]" />
            сб <input type="checkbox" asp-for="daysOfWeek[6]" />
            вс <input type="checkbox" asp-for="daysOfWeek[0]" />

        </div>
        <input type="submit" value="Удалить" />

    </form>
</div>

pre_registration/Views/Cupon/setCuponInterval.cshtml
@model pre_registration.Models.ViewModels.SetCuponIntervalViewModel
<h2 class="titleHeadRow">Добавление новых талонов для записи</h2>
<div>
    <div class="validation" asp-validation-summary="ModelOnly"></div>
    <form method="post" asp-controller="Cupon" asp-action="setCuponInterval" class="contentForm">

        @if (User.IsInRole("admin"))
        {
            <div class="contentDiv">
                <label asp-for="AreaId"></label><br />
                <select asp-for="AreaId" asp-items='new SelectList(ViewBag.Areas, "Id", "Name")' class="selectList setCuponIntervalInputItem"></select>
            </div>
        }
        <div>
            <label asp-for="beginDate"></label><br />
            <input type="date" asp-for="beginDate" class="setCuponIntervalInputItem" />
        </div>
        <div>
            <label asp-for="endDate"></label><br />
            <input type="date" asp-for="endDate"  class="setCuponIntervalInputItem" />
        </div>

        <div>
            <label asp-for="interval"></label><br />
            <input type="text" asp-for="interval" onkeyup="return checkNumberValue(this);" class="setCuponIntervalInputItem" />
        </div>
        <div class="contentDiv">
            пн<input type="checkbox" asp-for="daysOfWeek[1]" />
            вт <input type="checkbox" asp-for="daysOfWeek[2]" />
            ср<input type="checkbox" asp-for="daysOfWeek[3]" />
            чт <input type="checkbox" asp-for="daysOfWeek[4]" />
            пт <input type="checkbox" asp-for="daysOfWeek[5]" />
            сб <input type="checkbox" asp-for="daysOfWeek[6]" />
            вс <input type="checkbox" asp-for="daysOfWeek[0]" />

        </div>
        <div class="contentDiv">
            <label asp-for="beginTimeHours"></label>
            <select asp-for="beginTimeHours" asp-items='new SelectList(ViewBag.Hours)'></select>
            :
            <select asp-for="beginTimeMins" asp-items='new SelectList(ViewBag.Mins)'></select>
            <label asp-for="beginTimeMins"></label>
        </div>
        <div class="contentDiv">
            <label asp-for="endTimeHours"></label>
            <select asp-for="endTimeHours" asp-items='new SelectList(ViewBag.Hours)'></select>
            :

            <select asp-for="endTimeMins" asp-items='new SelectList(ViewBag.Mins)'></select>
            <label asp-for="endTimeMins"></label>
        </div>
        <input type="submit"  class="setCuponIntervalInputItem"  />

    </form>
</div>

pre_registration/Views/Cupon/viewCalendar.cshtml
@model List<pre_registration.Models.CuponDate>
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

@inject IHtmlLocalizer<SharedResource> SharedLocalizer
<div>
    @*<h2>Выберите дату</h2>*@
    <style type="text/css">
        td a {
            width: 100%;
            height: 100%;
            display: block;
            padding: 5px;
        }
    </style>
    <script>
        function showTimeLink()
        {
            $('.selectTime').show();
            $('.selectDate').hide();

        }

        $(document).ready(setCheckOutBar());
        @*$(document).ready(function () {
            $('.selectArea').load('@Url.Action("selectAreaForm", "Home")');
        });*@
    </script>
    <div>
        <br />
        @*<a class="backToSelectArea">Вернуться к выбору района</a>*@
        @{
            DateTime currentDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day);
            while (true)
            {
                if (currentDate.DayOfWeek != DayOfWeek.Monday)
                {
                    currentDate = currentDate.AddDays(-1);
                }
                else
                {
                    break;
                }
            }
        }
        <table border="1" class="table-calendar">
            @for (int i = 0; i < 5; i++)
            {
                <tr>
                    @for (int j = 0; j < 7; j++)
                    {


                        <td style="width:100px; height:100px;" class="tdItem">
                            @{
                                int freeCupons = 0;
                                foreach (var item in Model)
                                {
                                    if (currentDate.Date == item.date.Date)//&& item.date.TimeOfDay > DateTime.Now.TimeOfDay)
                                    {
                                        if (DateTime.Now.Date == currentDate.Date && item.date.TimeOfDay < DateTime.Now.TimeOfDay)
                                        {
                                            continue;

                                        }

                                        freeCupons++;
                                    }

                                }
                            }
                            <div id="@currentDate.Ticks">
                                @if (currentDate < DateTime.Now.AddDays(-1) || freeCupons == 0)
                                {
                                    <div style="text-align:center;">
                                        @currentDate.ToString("dd.MM")
                                    </div>
                                }
                                else
                                {
                                    <script>


                                    </script>
                                    <div class="deleteDayButtonDiv">

                                        <img src="~/images/delete_sign1600.png" alt="Удалить талоны на этот день" class="deleteDayButtonImage" onclick="deleteDay('@currentDate', '@currentDate.Ticks')" />
                                    </div>
                                    <div onclick="$('.selectTime').load('@Url.Action("viewTime", "Cupon", new { selectedDay = currentDate, areaId = ViewBag.SelectedArea})'); showTimeLink()">
                                        <div style="text-align:center;">
                                            @currentDate.ToString("dd.MM")
                                        </div>
                                        <div>
                                            @SharedLocalizer["FreePlaces"]
                                           
                                            @freeCupons
                                        </div>
                                    </div>


                                }

                            </div>
                        </td>



                        currentDate = currentDate.AddDays(1);
                    }

                </tr>
            }

        </table>
    </div>
</div>

<script>
    var selectedDayForDelete;
    var selectedDayDivId;
    $(document).ready(function () {
        if (isSuperUserCurrentArea()) {
            $('.deleteDayButtonDiv').show();
        }
        else
            $('.deleteDayButtonDiv').hide();

    });
    function deleteDay(currentDate, currentDiv) {

        ShowModalWindow('Удалить день?', 'Вы действительно хотите удалить', true);
        selectedDayForDelete = currentDate;
        selectedDayDivId = currentDiv;
    }
    //$(".deleteDayButtonImage").click(function () {

    //    ShowModalWindow('Удалить день?', 'Вы действительно хотите удалить', true);
    //    selectedDay =
    //});
    function isSuperUserCurrentArea() {
        var result;
        $.ajax({
            async: false,
            url: '/home/isSuperUserCurrentArea',
            type: 'GET',
            contentType: "application/json",
            success: function (data) {
                result = data;
            }
        });
        return result;

    }
    $('#modDialog').on('hide.bs.modal', function () {
        var btn = $(this).find("input[type=submit]:focus");
        if (btn.val() == "Подтвердить") {
            if (RemoveDayCupons(selectedDayForDelete)) {
                var currentDateDiv = new Date(selectedDayForDelete);
                var qwe = new Date(2008, 0, 12);
                var newDate = '';
                if (currentDateDiv.getDate() < 9)
                    newDate += '0' + currentDateDiv.getDate() + '.';
                else
                    newDate += currentDateDiv.getDate() + '.';
                if (currentDateDiv.getMonth() < 9)
                    newDate += '0' + (+currentDateDiv.getMonth().valueOf() + 1);
                else
                    newDate += +currentDateDiv.getMonth().valueOf() + 1;

                $("#" + selectedDayDivId).empty();
                $("#" + selectedDayDivId).html('<div style="text-align:center;">' + newDate + '</div>')
            }


        }
    });
    function RemoveDayCupons(day) {
        var result;
        $.ajax({
            async: false,
            url: '/Cupon/RemoveDayCupons?day=' + day,
            type: 'GET',
            contentType: "application/json",
            success: function (isDeleted) {
                result = isDeleted;
            }
        });
        return result;
    }
</script>

pre_registration/Views/Cupon/viewRegisterCupons.cshtml
@model List<pre_registration.Models.DataBaseModel.Order>
@{ 
    System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("ru-RU");
}
<h2 class="titleHeadRow">Зарегестрированные талоны</h2>
<table class="table">
    <tr>
        <th>id</th>
        @if (User.IsInRole("admin"))
        {
            <th>Район</th>
        }
        <th>Дата записи</th>
        <th>Дата талона</th>
        <th>Время талона</th>
        <th>Фамилия</th>
        <th>Имя</th>
        <th>Отчество</th>
        <th>Почта</th>
        <th>Телефон</th>
        <th>Коментарий</th>
    </tr>
    @foreach (var item in Model)
    {
    <tr>
        <td>@item.id</td>
        @if (User.IsInRole("admin"))
        {
        <td>@item.CuponDate.Area.Name</td>
        }

        <td>@item.OrderDate.ToShortDateString()</td>
        <td>@item.CuponDate.date.ToShortDateString()</td>
        <td>@item.CuponDate.date.ToShortTimeString()</td>
        <td>@item.Client.UserData.LastName</td>
        <td>@item.Client.UserData.FirstName</td>

        <td>@item.Client.UserData.SecondName</td>
        <td>@item.Client.UserData.EmailAdress </td>
        <td>@item.Client.UserData.Phone</td>
        <td>@item.Comment</td>
    </tr>
    }
</table>

pre_registration/Views/Cupon/viewTime.cshtml
@model List<pre_registration.Models.CuponDate>
    <script>
     
        function selectCuponTime(id) {
            $('.recordForm').load('@Url.Action("recordForm", "Home")' + '?id=' + id);
            $(".selectTime").hide();
            $(".selectDate").hide();
            $('.recordForm').show();

        }
        $(document).ready(setCheckOutBar());
    </script>
    <div>
        @*<h2>Выберите время</h2>*@
        @{
            int j = 1;
            System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("ru-RU");
        }
        @*<a class="backToSelectDate">Вернуться к выбору даты</a>*@

        @*@foreach (var item in Model)
        {
            if (DateTime.Now.Date == item.date.Date && item.date.TimeOfDay < DateTime.Now.TimeOfDay)
            {
                continue;

            }
            <div class="timeButton">
                <div  onclick="selectCuponTime('@item.id')" class="cuponTime">@item.date.ToShortTimeString()</div>
            </div>

                 j++;


        }*@
        <br /> <br />
        <table width="80%" align="center">
            @for (int i = 0; i < Model.Count;)
            {
                if (DateTime.Now.Date == Model[i].date.Date && Model[i].date.TimeOfDay < DateTime.Now.TimeOfDay)
                {
                    continue;

                }
                <tr>
                    @for (int k = 0; k < 5; k++)
                    {
                        if (i >= Model.Count)
                        {
                            <td></td>

                        }
                        else
                        {
                            <td>
                                <div class="timeButton">
                                    <div onclick="selectCuponTime('@Model[i].id')" class="cuponTime">@Model[i].date.ToShortTimeString()</div>

                                </div>
                            </td>
                            i++;
                        }
                    }
                </tr>
            }
        </table>
    </div>